name: 🧱 Build & Push API

on:
  push:
    branches: [main]
    paths:
      - 'src/api/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/api/**'
  workflow_dispatch:

jobs:
  build-and-push:
    name: 🐳 Build and Push API image
    uses: ./.github/workflows/build-image-reusable.yml
    with:
      image_name: sensitive-data-api
      build_context: ./src/api
    secrets: inherit
