name: 🌐 Build & Push Web

on:
  push:
    branches: [main]
    paths:
      - 'src/web/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/web/**'
  workflow_dispatch:

jobs:
  build-and-push:
    name: 🐳 Build and Push Web image
    uses: ./.github/workflows/build-image-reusable.yml
    with:
      image_name: sensitive-data-web
      build_context: ./src/web
    secrets: inherit
